# This is a basic workflow that is manually triggered

name: Harsco Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-and-deploy-on-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Generating Dev Build
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout Step
        id: checkout
        uses: actions/checkout@v1
      - name: Upload Local Build
        id: build
        run: ./build.sh
      - name: Get the output time
        run: echo "The time was ${{ env.BUILD_TIME }}"
      - name: Generate Local Build Number
        id: buildNumber
        run: ./generateBuildNumber.sh
      - name: Upload Build File
        uses: actions/upload-artifact@v3
        with:
          name: harsco file
          path: harsco.tar.gz   
      - name: Upload file to dev bucket
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: harsco.tar.gz
          AWS_REGION: 'us-east-1'
          S3_BUCKET: harsco-deployment.vensi.com
          S3_KEY: dev/${{ env.BUILD_NUMBER }}/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Deployed to DEV
        run: echo "Build Deployed to DEV"
  deploy-on-production:
    name: Generating Production Build
    needs: build-and-deploy-on-dev
    runs-on: ubuntu-latest
    steps:
      - name: build-and-deploy
        uses: actions/download-artifact@v3
        with:
          name: harsco file  
      - name: Generate Prod Build Number
        run: |
          BUILD_NUMBER=$(date +%Y%m%d)
          echo "BUILD_NUMBER=$(echo $BUILD_NUMBER)" >> $GITHUB_ENV    
      - name: Upload file to prod bucket
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: harsco.tar.gz
          AWS_REGION: 'us-east-1'
          S3_BUCKET: harsco-deployment.vensi.com
          S3_KEY: prd/${{ env.BUILD_NUMBER }}/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Deployed to Production
        run: echo "Build Deployed to PRODUCTION"  
