-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghVJwgnZ7UC5Gl/tiG9LzVvon+Q7n8fik47sKhoP+aKGgCgYIKoZIzj0DAQehRANCAAQ8fyKjIJcwxpSdJZSCKBqavTTMS7Lu+oi3/SaFC+YEtwcd/JltKuZSGm30MPtKiiNi7DtloYEJJe5kQpZj38uR
-----END PRIVATE KEY-----